# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 23:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre de Empresa')),
                ('cuit', models.IntegerField(verbose_name='CUIT')),
                ('company_type', models.IntegerField(choices=[(1, 'Empresa de Origen'), (2, 'Empresa de Destino')], verbose_name='Tipo de Empresa')),
                ('default', models.BooleanField(default=False, verbose_name='Marcar como Principal')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.FileField(upload_to=b'', verbose_name='Clave Privada')),
                ('certificate', models.FileField(upload_to=b'', verbose_name='Certificado')),
                ('wsaa_token', models.FileField(upload_to=b'', verbose_name='Token WSAA')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credenciales AFIP',
                'verbose_name_plural': 'Credenciales AFIP',
            },
        ),
    ]
