# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('codigo', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Cosecha',
                'verbose_name_plural': 'Cosechas',
            },
        ),
        migrations.CreateModel(
            name='COT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit_empresa', models.CharField(max_length=11, verbose_name='CUIT Empresa')),
                ('fecha_emision', models.CharField(blank=True, max_length=8, verbose_name='Fecha Emision (AAAAMMDD)')),
                ('codigo_unico', models.CharField(max_length=16, verbose_name='Codigo Unico (Carta de Porte)')),
                ('fecha_salida_transporte', models.CharField(max_length=8, verbose_name='Fecha Salida Transporte (AAAAMMDD)')),
                ('sujeto_generador', models.CharField(choices=[('E', 'Emisor'), ('D', 'Destinatario')], max_length=1, verbose_name='Sujeto Generador')),
                ('destinatario_consumidor_final', models.BooleanField(verbose_name='Destinatario Consumidor Final?')),
                ('destinatario_tenedor', models.BooleanField(verbose_name='Destinatario es Tenedor')),
                ('destino_domicilio_calle', models.CharField(max_length=40, verbose_name='Destino: Calle de Domicilio')),
                ('destino_domicilio_codigopostal', models.CharField(max_length=8, verbose_name='Destino: Codigo Postal')),
                ('destino_domicilio_localidad', models.CharField(max_length=50, verbose_name='Destino: Localidad')),
                ('entrega_domicilio_origen', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, verbose_name='Entrega Domicilio Origen')),
                ('origen_cuit', models.CharField(max_length=11, verbose_name='Origen CUIT')),
                ('origen_razon_social', models.CharField(max_length=50, verbose_name='Origen: Razon Social')),
                ('emisor_tenedor', models.BooleanField(verbose_name='Emisor es Tenedor')),
                ('origen_domicilio_calle', models.CharField(max_length=40, verbose_name='Origen: Calle de Domicilio')),
                ('origen_domicilio_codigopostal', models.CharField(max_length=8, verbose_name='Origen: Domicilio Codigo Postal')),
                ('origen_domicilio_localidad', models.CharField(max_length=50, verbose_name='Origen: Localidad')),
                ('transportista_cuit', models.CharField(max_length=11, verbose_name='CUIT Transportista')),
                ('producto_no_term_dev', models.BooleanField(default=False, verbose_name='Productos No Terminados / Devoluciones')),
                ('importe', models.CharField(max_length=10, verbose_name='Importe')),
                ('codigo_unico_producto', models.CharField(max_length=6, verbose_name='Codigo Unico Producto')),
                ('rentas_codigo_unidad_medida', models.IntegerField(choices=[(1, 'Kilogramos'), (2, 'Litros'), (3, 'Unidades'), (4, 'Metros Cuadrados'), (5, 'Metros'), (6, 'Metros Cubicos'), (7, 'Pares')], verbose_name='Codigo Unidad Medida')),
                ('cantidad', models.CharField(max_length=15, verbose_name='Cantidad')),
                ('propio_codigo_producto', models.CharField(max_length=25, verbose_name='Propio Codigo Producto')),
                ('propio_descripcion_producto', models.CharField(max_length=40, verbose_name='Propio Descripcion Producto')),
                ('propio_descripcion_unidad_medida', models.CharField(max_length=20, verbose_name='Propio Descripcion Unidad Medida')),
                ('cantidad_ajustada', models.CharField(max_length=15, verbose_name='Cantidad Ajustada')),
                ('generar_cot', models.BooleanField(default=False, verbose_name='Generar COT?')),
                ('cot_nombre', models.CharField(blank=True, max_length=30, verbose_name='COT Nombre')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Operacion')),
                ('numero_comprobante', models.CharField(blank=True, max_length=30, verbose_name='Numero de Comprobante')),
                ('codigo_integridad', models.CharField(blank=True, max_length=50, verbose_name='Codigo Integridad')),
                ('errores', models.TextField(blank=True, verbose_name='Errores')),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Parcial'), (2, 'Generado')], default=1, null=True, verbose_name='Estado del COT')),
            ],
            options={
                'verbose_name': 'COT',
                'verbose_name_plural': 'COTs',
            },
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_arba', models.CharField(max_length=12, verbose_name='Usuario ARBA')),
                ('pass_arba', models.CharField(max_length=30, verbose_name='Contrasena ARBA')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credenciales',
                'verbose_name_plural': 'Credenciales',
            },
        ),
        migrations.CreateModel(
            name='CTG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carta_de_porte', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='*Nro Carta de Porte')),
                ('remitente_comercial_como_canjeador', models.BooleanField(default=False, verbose_name='Rte Comercial actua como Canjeador?')),
                ('remitente_comercial_como_productor', models.BooleanField(default=False, verbose_name='Rte Comercial actua como Productor?')),
                ('peso_neto_carga', models.PositiveIntegerField(blank=True, null=True, verbose_name='*Peso Neto de Carga')),
                ('cant_horas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de Horas')),
                ('patente_vehiculo', models.CharField(blank=True, max_length=30, null=True, verbose_name='*Patente Vehiculo')),
                ('km_a_recorrer', models.PositiveIntegerField(blank=True, null=True, verbose_name='*Km a Recorrer')),
                ('turno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turno')),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Parcial'), (2, 'Generado'), (3, 'Anulado'), (4, 'Arribado')], default=1, null=True, verbose_name='Estado del CTG')),
                ('geolocalizacion', models.CharField(blank=True, max_length=150, verbose_name='Geo Localizacion de la Solicitud')),
                ('numero_ctg', models.CharField(blank=True, max_length=50, verbose_name='Nro CTG')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('fechahora', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fecha y Hora')),
                ('vigenciadesde', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vigencia Desde')),
                ('vigenciahasta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vigencia Hasta')),
                ('tarifareferencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tarifa Referencia')),
                ('errores', models.CharField(blank=True, max_length=200, null=True, verbose_name='Errores')),
                ('controles', models.CharField(blank=True, max_length=200, null=True, verbose_name='Controles')),
                ('codigo_operacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo Operacion')),
                ('accion', models.IntegerField(choices=[(1, 'CTG Parcial'), (2, 'Solicitar CTG')], default=1, verbose_name='Accion')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de CTG')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha de Operacion')),
                ('codigo_cosecha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cosecha', verbose_name='*Codigo Cosecha')),
            ],
            options={
                'verbose_name': 'CTG',
                'verbose_name_plural': 'CTGs',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre de Entidad')),
                ('cuit', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CUIT')),
                ('actua_como', models.IntegerField(blank=True, choices=[(1, 'Remitente Comercial'), (2, 'Destino'), (3, 'Destinatario'), (4, 'Corredor'), (5, 'Transportista')], null=True, verbose_name='Act\xfaa como')),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('codigo', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('codigo', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('codigo', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Operacion')),
                ('nombre', models.CharField(blank=True, max_length=120, verbose_name='Nombre de Operacion')),
                ('tipo_operacion', models.CharField(choices=[(1, 'CTG Solicitado'), (2, 'CTG carga parcial'), (3, 'CTG Anulado'), (4, 'COT')], max_length=20, verbose_name='Tipo de Operacion')),
                ('datos', models.TextField(verbose_name='Datos de la Operacion')),
            ],
            options={
                'verbose_name': 'Operacion',
                'verbose_name_plural': 'Operaciones',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codigo', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Provincia_ARBA',
            fields=[
                ('codigo', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=25, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Provicia ARBA',
                'verbose_name_plural': 'Provincias ARBA',
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Provincia'),
        ),
        migrations.AddField(
            model_name='ctg',
            name='codigo_especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Especie', verbose_name='*Codigo Especie'),
        ),
        migrations.AddField(
            model_name='ctg',
            name='codigo_localidad_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_localidad_destino', to='backend.Localidad', verbose_name='*Codigo Localidad Destino'),
        ),
        migrations.AddField(
            model_name='ctg',
            name='codigo_localidad_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_localidad_origen', to='backend.Localidad', verbose_name='*Codigo Localidad Origen'),
        ),
        migrations.AddField(
            model_name='ctg',
            name='cuit_corredor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_corredor', to='backend.Entidad', verbose_name='Cuit Corredor'),
        ),
        migrations.AddField(
            model_name='ctg',
            name='cuit_destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_destinatario', to='backend.Entidad', verbose_name='*Cuit Destinatario'),
        ),
        migrations.AddField(
            model_name='ctg',
            name='cuit_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_destino', to='backend.Entidad', verbose_name='*Cuit Destino'),
        ),
        migrations.AddField(
            model_name='ctg',
            name='cuit_remitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_remitente', to='backend.Entidad', verbose_name='Cuit Remitente Comercial'),
        ),
        migrations.AddField(
            model_name='ctg',
            name='cuit_transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_transportista', to='backend.Entidad', verbose_name='Cuit Tranportista'),
        ),
        migrations.AddField(
            model_name='ctg',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg', to='backend.Operacion'),
        ),
        migrations.AddField(
            model_name='ctg',
            name='usuario_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante'),
        ),
        migrations.AddField(
            model_name='cot',
            name='destino_domicilio_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincia_destino', to='backend.Provincia_ARBA'),
        ),
        migrations.AddField(
            model_name='cot',
            name='origen_domicilio_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincia_origen', to='backend.Provincia_ARBA'),
        ),
        migrations.AddField(
            model_name='cot',
            name='usuario_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante'),
        ),
    ]
