# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctg',
            name='codigo_especie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.Especie', verbose_name='Codigo Especie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ctg',
            name='codigo_cosecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cosecha', verbose_name='Codigo Cosecha'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='codigo_localidad_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctg_localidad_destino', to='backend.Localidad', verbose_name='Codigo Localidad Destino'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='codigo_localidad_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctg_localidad_origen', to='backend.Localidad', verbose_name='Codigo Localidad Origen'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='km_a_recorrer',
            field=models.PositiveIntegerField(verbose_name='Km a Recorrer'),
        ),
    ]
