# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='certificate_text',
            field=models.TextField(default='', verbose_name='Text de Certificado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='key_text',
            field=models.TextField(default='', verbose_name='Texto de Clave Privada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credential',
            name='wsaa_token',
            field=models.FileField(upload_to=b'', verbose_name='Token WSAA (TA)'),
        ),
    ]
