# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cot',
            name='codigo_unico',
        ),
        migrations.AddField(
            model_name='cot',
            name='nro_comprobante',
            field=models.CharField(default='', max_length=12, verbose_name='Nro Comprobante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cot',
            name='tipo_comprobante',
            field=models.CharField(choices=[(b'74 P', b'Carta de Porte'), (b'91 R', b'Remito R'), (b'01 A', b'Factura A'), (b'60 A', b'Cuenta de Venta y Liquido Producto A'), (b'94 X', b'Remito X'), (b'06 B', b'Factura B'), (b'92 C', b'Factura C'), (b'51 M', b'Factura M'), (b'61 B', b'Cuenta de Venta y Liquido Producto B'), (b'93 C', b'Cuenta de Venta y Liquido Producto C'), (b'58 M', b'Cuenta de Venta y Liquido Producto M'), (b'95 G', b'Guia Unica de Traslado'), (b'97 E', b'Documento Equivalente')], default='', max_length=4, verbose_name='Tipo de Comprobante'),
            preserve_default=False,
        ),
    ]
