# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 16:38
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=150, verbose_name='Nombre y Apellido')),
                ('usuario_arba', models.CharField(blank=True, max_length=12, verbose_name='Usuario ARBA')),
                ('pass_arba', models.CharField(blank=True, max_length=30, verbose_name='Contrasena ARBA')),
                ('cuit_solicitante', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999999)], verbose_name='CUIT Solicitante')),
                ('credenciales_produccion', models.BooleanField(default=True, verbose_name='Credenciales en Produccion')),
                ('afip_habilitado', models.BooleanField(default=False, verbose_name='Servicios AFIP habilitados ?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credenciales',
                'verbose_name_plural': 'Credenciales',
            },
        ),
        migrations.RemoveField(
            model_name='credencial',
            name='user',
        ),
        migrations.DeleteModel(
            name='Credencial',
        ),
    ]
