# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170831_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctg',
            name='cant_horas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de Horas'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='cuit_remitente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_remitente', to='backend.Entidad', verbose_name='Cuit Remitente Comercial'),
        ),
    ]
