# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20171017_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cot',
            name='destino_domicilio_provincia',
            field=models.CharField(choices=[(b'A', b'Salta'), (b'B', b'Buenos Aires'), (b'C', b'Capital Federal'), (b'D', b'San Luis'), (b'E', b'Entre Rios'), (b'F', b'La Rioja'), (b'G', b'Santiago del Estero'), (b'H', b'Chaco'), (b'J', b'San Juan'), (b'K', b'Catamarca'), (b'L', b'La Pampa'), (b'M', b'Mendoza'), (b'N', b'Misiones'), (b'P', b'Formosa'), (b'Q', b'Neuquen'), (b'R', b'Rio Negro'), (b'S', b'Santa Fe'), (b'T', b'Tucuman'), (b'U', b'Chubut'), (b'V', b'T.N.T. del Fuego'), (b'W', b'Corrientes'), (b'X', b'Cordoba'), (b'Y', b'Jujuy'), (b'Z', b'Santa Cruz')], max_length=1, verbose_name='Provincia Destino'),
        ),
        migrations.AlterField(
            model_name='cot',
            name='origen_domicilio_provincia',
            field=models.CharField(choices=[(b'A', b'Salta'), (b'B', b'Buenos Aires'), (b'C', b'Capital Federal'), (b'D', b'San Luis'), (b'E', b'Entre Rios'), (b'F', b'La Rioja'), (b'G', b'Santiago del Estero'), (b'H', b'Chaco'), (b'J', b'San Juan'), (b'K', b'Catamarca'), (b'L', b'La Pampa'), (b'M', b'Mendoza'), (b'N', b'Misiones'), (b'P', b'Formosa'), (b'Q', b'Neuquen'), (b'R', b'Rio Negro'), (b'S', b'Santa Fe'), (b'T', b'Tucuman'), (b'U', b'Chubut'), (b'V', b'T.N.T. del Fuego'), (b'W', b'Corrientes'), (b'X', b'Cordoba'), (b'Y', b'Jujuy'), (b'Z', b'Santa Cruz')], max_length=1, verbose_name='Provincia Origen'),
        ),
        migrations.DeleteModel(
            name='Provincia_ARBA',
        ),
    ]
