# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170822_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carta_de_porte', models.CharField(max_length=50, verbose_name='Nro Carta de Porte')),
                ('numero_ctg', models.CharField(max_length=50, verbose_name='Nro Carta de Porte')),
                ('codigo_localidad_origen', models.PositiveIntegerField(verbose_name='Codigo Localidad Origen')),
                ('codigo_localidad_destino', models.PositiveIntegerField(verbose_name='Codigo Localidad Destino')),
                ('codigo_cosecha', models.PositiveIntegerField(verbose_name='Codigo Cosecha')),
                ('peso_neto_carga', models.PositiveIntegerField(verbose_name='Peso Neto de Carga')),
                ('cant_horas', models.PositiveIntegerField(blank=True, verbose_name='Cantidad de Horas')),
                ('patente_vehiculo', models.CharField(blank=True, max_length=30, verbose_name='Patente Vehiculo')),
                ('km_a_recorrer', models.PositiveIntegerField(blank=True, verbose_name='Km a Recorrer')),
                ('remitente_comercial_como_canjeador', models.CharField(blank=True, max_length=100, verbose_name='Remitente comercial Canjeador')),
                ('remitente_comercial_como_productor', models.CharField(blank=True, max_length=100, verbose_name='Remitente comercial Canjeador')),
                ('turno', models.CharField(blank=True, max_length=50, verbose_name='Turno')),
                ('estado', models.IntegerField(choices=[(1, 'Sin Generar'), (2, 'Generado'), (3, 'Datos Pendientes'), (4, 'Anulado'), (5, 'Arribado')], default=1, verbose_name='Estado del CTG')),
                ('fecha', models.DateField(blank=True, verbose_name='Fecha de Obtencion del CTG')),
                ('geolocalizacion', models.CharField(blank=True, max_length=150, verbose_name='Geo Localizacion de la Solicitud')),
                ('cuit_canjeador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctg_cajeador', to='backend.Company', verbose_name='Cuit Canjeador')),
                ('cuit_corredor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_corredor', to='backend.Company', verbose_name='Cuit Corredor')),
                ('cuit_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctg_destinatario', to='backend.Company', verbose_name='Cuit Destinatario')),
                ('cuit_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctg_destino', to='backend.Company', verbose_name='Cuit Destino')),
                ('cuit_transportista', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_transportista', to='backend.Company', verbose_name='Cuit Tranportista')),
            ],
            options={
                'verbose_name': 'CTG',
                'verbose_name_plural': 'CTGs',
            },
        ),
        migrations.AlterField(
            model_name='credential',
            name='certificate_text',
            field=models.TextField(blank=True, verbose_name='Text de Certificado'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='key_text',
            field=models.TextField(blank=True, verbose_name='Texto de Clave Privada'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='wsaa_token',
            field=models.FileField(blank=True, upload_to=b'', verbose_name='Token WSAA (TA)'),
        ),
    ]
