# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170823_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='key_text',
        ),
        migrations.AlterField(
            model_name='credential',
            name='key',
            field=models.CharField(max_length=60, verbose_name='Clave Privada'),
        ),
    ]
