# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171017_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cot',
            name='fecha_emision',
            field=models.CharField(max_length=8, verbose_name='Fecha Emision (AAAAMMDD)'),
        ),
    ]
