# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170831_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctg',
            name='cuit_corredor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_corredor', to='backend.Entidad', verbose_name='Cuit Corredor'),
        ),
    ]
