# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20170823_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='key',
            field=models.FileField(upload_to=b'', verbose_name='Clave Privada'),
        ),
    ]
