# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 00:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20171017_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='cot',
            name='destinatario_cuit',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999999)], verbose_name='Destinatario Cuit'),
        ),
        migrations.AddField(
            model_name='cot',
            name='destinatario_razon_social',
            field=models.CharField(blank=True, default=' ', max_length=50, verbose_name='Destinatario Razon Social'),
        ),
        migrations.AddField(
            model_name='cot',
            name='file_path',
            field=models.CharField(default='', max_length=200, verbose_name='Archivo de Intercambio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cot',
            name='patente_vehiculo',
            field=models.CharField(blank=True, default=' ', max_length=7, verbose_name='Patente Vehiculo'),
        ),
#         migrations.AlterField(
#             model_name='cot',
#             name='nro_comprobante',
#             field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='Nro Comprobante'),
#         ),
    ]
