# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20170831_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctg',
            name='cuit_remitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_remitente', to='backend.Entidad', verbose_name='Cuit Remitente Comercial'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='cuit_transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_transportista', to='backend.Entidad', verbose_name='Cuit Tranportista'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='patente_vehiculo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Patente Vehiculo'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='turno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Turno'),
        ),
    ]
