# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_auto_20170823_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='ctg',
            name='usuario_solicitante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante'),
            preserve_default=False,
        ),
    ]
