# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 00:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20171019_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cot',
            name='nro_comprobante',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='Nro Comprobante'),
        ),
    ]
