# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_auto_20170901_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='ctg',
        ),
        migrations.AddField(
            model_name='operacion',
            name='datos',
            field=models.TextField(default='', verbose_name='Datos de la Operacion'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='usuario_solicitante',
        ),
        migrations.AddField(
            model_name='entidad',
            name='usuario_solicitante',
            field=models.ForeignKey(null=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante'),
            preserve_default=False,
        ),
    ]
