# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20170823_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cuit',
            field=models.CharField(max_length=20, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='cuit_canjeador',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_cajeador', to='backend.Company', verbose_name='Cuit Canjeador'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='numero_ctg',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nro CTG'),
        ),
    ]
