# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20171019_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cot',
            name='patente_vehiculo',
            field=models.CharField(blank=True, default=' ', max_length=7, null=True, verbose_name='Patente Vehiculo'),
        ),
    ]
