# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20171019_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cot',
            name='destinatario_razon_social',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Destinatario Razon Social'),
        ),
    ]
