# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20170906_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctg',
            name='codigo_operacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo Operacion'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='codigo_cosecha',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cosecha', verbose_name='*Codigo Cosecha'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='codigo_especie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Especie', verbose_name='*Codigo Especie'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='codigo_localidad_destino',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_localidad_destino', to='backend.Localidad', verbose_name='*Codigo Localidad Destino'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='codigo_localidad_origen',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_localidad_origen', to='backend.Localidad', verbose_name='*Codigo Localidad Origen'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='cuit_destinatario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_destinatario', to='backend.Entidad', verbose_name='*Cuit Destinatario'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='cuit_destino',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_destino', to='backend.Entidad', verbose_name='*Cuit Destino'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Sin Generar'), (2, 'Generado'), (3, 'Datos Pendientes'), (4, 'Anulado'), (5, 'Arribado')], default=1, verbose_name='Estado del CTG'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='km_a_recorrer',
            field=models.PositiveIntegerField(blank=True, verbose_name='*Km a Recorrer'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='numero_carta_de_porte',
            field=models.CharField(blank=True, max_length=12, verbose_name='*Nro Carta de Porte'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='patente_vehiculo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='*Patente Vehiculo'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='peso_neto_carga',
            field=models.PositiveIntegerField(blank=True, verbose_name='*Peso Neto de Carga'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='tipo_operacion',
            field=models.CharField(choices=[(1, 'Solicitud de CTG'), (2, 'Solicitud de CTG con Dato Pendiente'), (3, 'Anulacion de CTG')], max_length=20, verbose_name='Tipo de Operacion'),
        ),
    ]
