# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20170906_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctg',
            name='codigo_especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Especie', verbose_name='*Codigo Especie'),
        ),
    ]
