# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20180115_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='codigo_arba',
            field=models.CharField(max_length=1, unique=True, verbose_name='Codigo ARBA'),
        ),
        migrations.AlterField(
            model_name='cot',
            name='destino_domicilio_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cot_provincia_destino', to='backend.Provincia', to_field='codigo_arba', verbose_name='Provincia de Destino'),
        ),
        migrations.AlterField(
            model_name='cot',
            name='origen_domicilio_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cot_provincia_origen', to='backend.Provincia', to_field='codigo_arba', verbose_name='Provincia de Origen'),
        )
    ]
