# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20180115_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cot',
            name='destino_domicilio_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cot_localidad_destino', to='backend.Localidad', verbose_name='Localidad de Destino'),
        ),
        migrations.AlterField(
            model_name='cot',
            name='origen_domicilio_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cot_localidad_origen', to='backend.Localidad', verbose_name='Localidad de Origen'),
        ),
    ]
