# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20170906_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctg',
            name='codigo_cosecha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cosecha', verbose_name='*Codigo Cosecha'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='codigo_localidad_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_localidad_destino', to='backend.Localidad', verbose_name='*Codigo Localidad Destino'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='codigo_localidad_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_localidad_origen', to='backend.Localidad', verbose_name='*Codigo Localidad Origen'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='cuit_destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_destinatario', to='backend.Entidad', verbose_name='*Cuit Destinatario'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='cuit_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_destino', to='backend.Entidad', verbose_name='*Cuit Destino'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Sin Generar'), (2, 'Generado'), (3, 'Datos Pendientes'), (4, 'Anulado'), (5, 'Arribado')], default=1, null=True, verbose_name='Estado del CTG'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='km_a_recorrer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='*Km a Recorrer'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='peso_neto_carga',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='*Peso Neto de Carga'),
        ),
    ]
