# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20170906_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='actua_como',
            field=models.IntegerField(blank=True, choices=[(1, 'Remitente Comercial'), (2, 'Destino'), (3, 'Destinatario'), (4, 'Corredor'), (5, 'Transportista')], null=True, verbose_name='Act\xfaa como'),
        ),
    ]
