# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20180125_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencial',
            name='alias',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre y Apellido'),
        ),
    ]
