# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_credencial_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencial',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to=settings.AUTH_USER_MODEL),
        ),
    ]
