# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20170907_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='COT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit_empresa', models.CharField(max_length=11, verbose_name='CUIT Empresa')),
                ('fecha_emision', models.DateField(verbose_name='Fecha Emision')),
                ('codigo_unico', models.CharField(max_length=16, verbose_name='Codigo Unico')),
                ('fecha_salida_transporte', models.DateField(verbose_name='Fecha Salida Transporte')),
                ('sujeto_generador', models.CharField(choices=[('E', 'Emisor'), ('D', 'Destinatario')], max_length=1, verbose_name='Sujeto Generador')),
                ('destinatario_consumidor_final', models.BooleanField(verbose_name='Destinatario Consumidor Final?')),
                ('destinatario_tenedor', models.BooleanField(verbose_name='Destinatario es Tenedor')),
                ('destino_domicilio_calle', models.CharField(max_length=40, verbose_name='Destino: Calle de Domicilio')),
                ('destino_domicilio_codigopostal', models.CharField(max_length=8, verbose_name='Destino: Codigo Postal')),
                ('destino_domicilio_localidad', models.CharField(max_length=50, verbose_name='Destino: Localidad')),
                ('entrega_domicilio_origen', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, verbose_name='Entrega Domicilio Origen')),
                ('origen_cuit', models.CharField(max_length=11, verbose_name='Origen CUIT')),
                ('origen_razon_social', models.CharField(max_length=50, verbose_name='Origen: Razon Social')),
                ('emisor_tenedor', models.BooleanField(verbose_name='Emisor es Tenedor')),
                ('origen_domicilio_calle', models.CharField(max_length=40, verbose_name='Origen: Calle de Domicilio')),
                ('origen_domicilio_codigopostal', models.CharField(max_length=8, verbose_name='Origen: Domicilio Codigo Postal')),
                ('origen_domicilio_localidad', models.CharField(max_length=50, verbose_name='Origen: Localidad')),
                ('transportista_cuit', models.CharField(max_length=11, verbose_name='CUIT Transportista')),
                ('producto_no_term_dev', models.BooleanField(default=False, verbose_name='Productos No Terminados / Devoluciones')),
                ('importe', models.CharField(max_length=10, verbose_name='Importe')),
                ('codigo_unico_producto', models.CharField(max_length=6, verbose_name='Codigo Unico Producto')),
                ('rentas_codigo_unidad_medida', models.CharField(choices=[(1, 'Kilogramos'), (2, 'Litros'), (3, 'Unidades'), (4, 'Metros Cuadrados'), (5, 'Metros'), (6, 'Metros Cubicos'), (7, 'Pares')], max_length=1, verbose_name='Codigo Unidad Medida')),
                ('cantidad', models.CharField(max_length=15, verbose_name='Cantidad')),
                ('propio_codigo_producto', models.CharField(max_length=25, verbose_name='Propio Codigo Producto')),
                ('propio_descripcion_producto', models.CharField(max_length=40, verbose_name='Propio Descripcion Producto')),
                ('propio_descripcion_unidad_medida', models.CharField(max_length=20, verbose_name='Propio Descripcion Unidad Medida')),
                ('cantidad_ajustada', models.CharField(max_length=15, verbose_name='Cantidad Ajustada')),
                ('generar_cot', models.BooleanField(default=False, verbose_name='Generar COT?')),
                ('cot_nombre', models.CharField(max_length=30, verbose_name='COT Nombre')),
            ],
            options={
                'verbose_name': 'COT',
                'verbose_name_plural': 'COTs',
            },
        ),
        migrations.CreateModel(
            name='Provincia_ARBA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=25, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Provicia ARBA',
                'verbose_name_plural': 'Provincias ARBA',
            },
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AddField(
            model_name='ctg',
            name='operacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Operacion'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre de Operacion'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='tipo_operacion',
            field=models.CharField(choices=[(1, 'CTG'), (2, 'CTG carga parcial'), (3, 'Anulacion de CTG'), (4, 'COT')], max_length=20, verbose_name='Tipo de Operacion'),
        ),
        migrations.AddField(
            model_name='cot',
            name='destino_domicilio_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincia_destino', to='backend.Provincia_ARBA'),
        ),
        migrations.AddField(
            model_name='cot',
            name='origen_domicilio_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincia_origen', to='backend.Provincia_ARBA'),
        ),
    ]
