# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20170912_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='cuit',
            field=models.CharField(max_length=11, verbose_name='CUIT'),
        ),
    ]
