# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20170912_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctg',
            name='accion',
            field=models.CharField(choices=[(1, 'Solicitar CTG'), (2, 'CTG Parcial')], default=2, max_length=1, verbose_name='Accion'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Operacion'),
        ),
    ]
