# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20170912_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctg',
            name='accion',
            field=models.IntegerField(choices=[(1, 'CTG Parcial'), (2, 'Solicitar CTG')], default=1, verbose_name='Accion'),
        ),
    ]
