# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20170912_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='cot',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Operacion'),
        ),
        migrations.AddField(
            model_name='ctg',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Fecha de Operacion'),
        ),
    ]
