# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20170913_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosecha',
            name='id',
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='codigo',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
    ]
