# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20170914_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='provincia_arba',
            name='id',
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cuit',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='codigo',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='codigo',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='codigo',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigo',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='provincia_arba',
            name='codigo',
            field=models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
    ]
