# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0023_auto_20170914_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='cot',
            name='usuario_solicitante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante'),
            preserve_default=False,
        ),
    ]
