# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_cot_usuario_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cot',
            name='codigo_unico_producto',
            field=models.IntegerField(max_length=6, verbose_name='Codigo Unico Producto'),
        ),
    ]
