# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20170914_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cot',
            name='codigo_unico_producto',
            field=models.CharField(max_length=6, verbose_name='Codigo Unico Producto'),
        ),
        migrations.AlterField(
            model_name='cot',
            name='rentas_codigo_unidad_medida',
            field=models.IntegerField(choices=[(1, 'Kilogramos'), (2, 'Litros'), (3, 'Unidades'), (4, 'Metros Cuadrados'), (5, 'Metros'), (6, 'Metros Cubicos'), (7, 'Pares')], max_length=1, verbose_name='Codigo Unidad Medida'),
        ),
    ]
