# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20170914_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='cot',
            name='codigo_integridad',
            field=models.CharField(blank=True, max_length=50, verbose_name='Codigo Integridad'),
        ),
        migrations.AddField(
            model_name='cot',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numero de Comprobante'),
        ),
        migrations.AddField(
            model_name='cot',
            name='remitos',
            field=models.TextField(blank=True, verbose_name='Remitos'),
        ),
        migrations.AlterField(
            model_name='cot',
            name='codigo_unico',
            field=models.CharField(max_length=16, verbose_name='Codigo Unico (Carta de Porte)'),
        ),
        migrations.AlterField(
            model_name='cot',
            name='fecha_emision',
            field=models.DateField(verbose_name='Fecha Emision (AAAAMMDD)'),
        ),
        migrations.AlterField(
            model_name='cot',
            name='fecha_salida_transporte',
            field=models.DateField(verbose_name='Fecha Salida Transporte (AAAAMMDD)'),
        ),
    ]
