# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20170914_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cot',
            name='fecha_emision',
            field=models.CharField(max_length=8, verbose_name='Fecha Emision (AAAAMMDD)'),
        ),
        migrations.AlterField(
            model_name='cot',
            name='fecha_salida_transporte',
            field=models.CharField(max_length=8, verbose_name='Fecha Salida Transporte (AAAAMMDD)'),
        ),
    ]
