# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20170915_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctg',
            name='numero_carta_de_porte',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='*Nro Carta de Porte'),
        ),
    ]
