# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 19:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20170915_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cot',
            name='cot_nombre',
            field=models.CharField(blank=True, max_length=30, verbose_name='COT Nombre'),
        ),
        migrations.AlterField(
            model_name='cot',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Operacion'),
        ),
        migrations.AlterField(
            model_name='cot',
            name='fecha_emision',
            field=models.CharField(blank=True, max_length=8, verbose_name='Fecha Emision (AAAAMMDD)'),
        ),
    ]
