# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20170915_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cot',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Operacion'),
        ),
    ]
