# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20170915_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cot',
            old_name='remitos',
            new_name='errores',
        ),
        migrations.AddField(
            model_name='cot',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Parcial'), (2, 'Generado')], default=1, null=True, verbose_name='Estado del COT'),
        ),
    ]
