# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20170915_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cot',
            name='errores',
            field=models.TextField(blank=True, verbose_name='Errores'),
        ),
        migrations.AlterField(
            model_name='ctg',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Fecha de Operacion'),
        ),
    ]
